### ISSUE TITLE
Upgrade 1.11

### ISSUE THREAD

**Issue by lucasdiedrich** [devinsolutions/docker-osticket#3]
Please, can you upgrade the package to version 1.11 final release?

Thanks

**Comment by lubo** [comment]
Hi @lucasdiedrich, there's #2 pending review. The PR contains some potentially breaking changes, which I didn't wanna publish in-between patch level releases and I'm hoping to get it merged tomorrow. I don't expect things to change much if at all, so feel free to test it out. Any feedback before the merge would be highly appreciated.
