### ISSUE TITLE
Battling to update Dockerfile for 1.16.3

### ISSUE THREAD

**Issue by PhatWheZ** [devinsolutions/docker-osticket#34]
Hi there, Great to see a working container of osTicket! Was wanting to try build one but always struggled for some reason?

Anyways. I cloned your repo and tried to update the SHA256 and version from 1.16.1 to 1.16.3 but when trying to build the Dockerfile, it keeps throwing errors.
Do you have any suggestions on how I can push this to the latest stable? or if we can set it as an ENV going forward on your repo?

**Comment by adam-dej** [comment]
Hi, I'll be updating this image to `1.16.3` in the next few days. Please, post the exact errors you are experiencing if you still want to build your own image / don't want to wait for me to upgrade it, I'll try to help.

**Comment by PhatWheZ** [comment]
Happy to wait if this is already on your todo list.
Was using a fresh install of Docker on Ubuntu 20.04 LTS with nothing else installed, so not 100% sure why it failed.

The output failed here FYI
```
#11 5.284 + rm osTicket.zip
#11 5.294 + mkdir /usr/local/src
#11 5.295 + mv upload /usr/local/src/osticket
#11 5.295 + patch -d /usr/local/src/osticket -Np1 -i /tmp/osticket-glob-brace.patch
#11 5.296 patching file include/class.plugin.php
#11 5.296 Reversed (or previously applied) patch detected!  Skipping patch.
#11 5.296 1 out of 1 hunk ignored -- saving rejects to file include/class.plugin.php.rej
------
executor failed running [/bin/sh -c set -ex;         apk add --no-cache --virtual .install-deps         patch     ;         wget -q -O osTicket.zip https://github.com/osTicket/osTicket/releases/download/v${OSTICKET_VERSION}/osTicket-v${OSTICKET_VERSION}.zip;     echo "${OSTICKET_SHA256SUM}  osTicket.zip" | sha256sum -c;     unzip osTicket.zip 'upload/*';     rm osTicket.zip;     mkdir /usr/local/src;     mv upload /usr/local/src/osticket;     patch -d /usr/local/src/osticket -Np1 -i /tmp/osticket-glob-brace.patch;     cp -al /usr/local/src/osticket/. /var/www/html;     rm -r /var/www/html/setup;         for lang in ar_EG ar_SA az bg bn bs ca cs da de el es_AR es_ES es_MX et eu fa fi fr gl he hi         hr hu id is it ja ka km ko lt lv mk mn ms nl no pl pt_BR pt_PT ro ru sk sl sq sr sr_CS         sv_SE sw th tr uk ur_IN ur_PK vi zh_CN zh_TW; do         wget -q -O /var/www/html/include/i18n/${lang}.phar             https://s3.amazonaws.com/downloads.osticket.com/lang/1.14.x/${lang}.phar;     done;         apk del .install-deps;     rm -rf /var/cache/apk/*]: exit code: 1
```

**Comment by adam-dej** [comment]
I see. In `1.16.1` we needed to patch the use of `GLOB_BRACE` flag, since it won't work on Alpine. They've since removed it from the upstream codebase (https://github.com/osTicket/osTicket/pull/6115), so the patch won't apply anymore. https://github.com/devinsolutions/docker-osticket/commit/73521434d2ce2dbbfbbd03a4002db51fd7978e68 can therefore be reverted (probably, I'll need to test it first).

**Comment by adam-dej** [comment]
The image was updated to `1.16.3` in #35

**Comment by Zeks** [comment]
@PhatWheZ you have comments locked in your creeper world videos on youtube so there can be no discussion

(sorry for off topic, we can't reach phatwhez in any other way)

**Comment by PhatWheZ** [comment]
@Zeks and all. Sorry had "Approved for kids" enabled. Have changed that setting as per Youtube documentation and seems comments are now enabled. Chat on youtube :)
