### ISSUE TITLE
Help Desk Audit plugin crashes on Dashboard->Audit Logs

### ISSUE THREAD

**Issue by Cronist** [devinsolutions/docker-osticket#36]
When enabled "Help Desk Audit" plugin, works on agents and tickets web interfaces. 

But it crashes on  Admin Panel -> Dashboard -> Audit Logs.

This is the error displayed.

`Fatal error: Uncaught Error: Failed opening required 'phar:///var/www/html/include//plugins/audit.phar/class.audit.php' (include_path='./:/var/www/html/include/:/var/www/html/include/pear/') in /var/www/html/scp/audits.php:19 Stack trace: #0 {main} thrown in /var/www/html/scp/audits.php on line 19`

this is the content of the related directories

/var/www/html # ls -al include/plugins/
total 52
drwxr-xr-x    1 root     root          4096 Sep  2 04:27 .
drwxr-xr-x    1 root     root          4096 Sep  6 18:30 ..
-rw-r--r--    2 root     root             0 Sep  2 04:27 .keep
drwxrwxr-x    3 root     root          4096 May 31 10:48 audit
drwxrwxr-x    3 root     root          4096 Sep  2 04:27 auth-2fa
drwxrwxr-x    3 root     root          4096 Sep  2 04:27 auth-cas
drwxrwxr-x    3 root     root          4096 Sep  2 04:27 auth-ldap
drwxrwxr-x    3 root     root          4096 Sep  2 04:27 auth-oauth
drwxrwxr-x    2 root     root          4096 May 31 10:48 auth-passthru
drwxrwxr-x    2 root     root          4096 May 31 10:48 auth-password-policy
drwxrwxr-x    2 root     root          4096 Jul 18  2017 slack
drwxrwxr-x    2 root     root          4096 May 31 10:48 storage-fs
drwxrwxr-x    3 root     root          4096 Sep  2 04:27 storage-s3
-rw-r--r--    2 root     root          1194 Sep  2 04:27 updates.pem

/var/www/html # ls -al include/plugins/audit/
total 68
drwxrwxr-x    3 root     root          4096 May 31 10:48 .
drwxr-xr-x    1 root     root          4096 Sep  2 04:27 ..
-rw-rw-r--    1 root     root          7312 May 31 10:48 audit.php
-rw-rw-r--    1 root     root         37994 May 31 10:48 class.audit.php
-rw-rw-r--    1 root     root           647 May 31 10:48 config.php
-rw-rw-r--    1 root     root           418 May 31 10:48 plugin.php
drwxrwxr-x    2 root     root          4096 May 31 10:48 templates
/var/www/html #

**Comment by lubo** [comment]
I've tried the plugin on the latest image version and I don't see the same problem.
