### ISSUE TITLE
Default admin login not working

### ISSUE THREAD

**Issue by Treawlony** [devinsolutions/docker-osticket#37]
When using the default logins from the settings, it does not enter:

![image](https://user-images.githubusercontent.com/87983359/192985306-95203ba5-8914-4f53-a3de-774d99408761.png)

**Comment by Treawlony** [comment]
I also tried with some env variables but same result. Typing anything still leave me stuck there

**Comment by Treawlony** [comment]
actually no login or user registration pages works

**Comment by mpolinowski** [comment]
The user login is set here:

https://github.com/devinsolutions/docker-osticket/blob/master/root/usr/local/src/osticket/setup/install.php

They will be overwritten by your Docker env variables (`ADMIN_USERNAME`, `ADMIN_PASSWORD`) if you set them in your Docker or Docker-Compose file. Also, if you have an existing database or import your old database you will end up with your old logins.

**Comment by lubo** [comment]
You need to use `/scp/login.php`, which works for me with the current image. Since no information indicating that there's an issue in this image was provided, I'm closing this issue.
