### ISSUE TITLE
TimeZone Kyiv

### ISSUE THREAD

**Issue by chodorenko** [devinsolutions/docker-osticket#42]
After select  in admin panel timezone Kyiv Osticket not correct work and not accept login admin

**Comment by lubo** [comment]
I do see `jquery-3.7.0.min.js?ea462cb:2 Uncaught TypeError: $(...).select2 is not a function` in browser console, but that seems to be a bug in osTicket, not this image. Please, report the problem to osTicket or provide a proof that this is indeed an issue in this image.
