### ISSUE TITLE
Data path mapping

### ISSUE THREAD

**Issue by thesorskod** [devinsolutions/docker-osticket#43]
Hello,

currently running 'devinsolutions/osticket'

![installation_ver](https://user-images.githubusercontent.com/96728533/230637942-c74b8923-7043-4dc6-a206-d561b758ec42.png)

Not sure if this is normal, but the 'Data Path' mapping on has not data/file. 
![data_map](https://user-images.githubusercontent.com/96728533/230638003-8c43e059-25e9-4477-94c5-c4374fea171b.png)

navigating to '/mnt/user/appdata/osticket/' has no data/files is this normal while using mysql/mariadb database?

**Comment by thesorskod** [comment]
any advise on this issue?

**Comment by lubo** [comment]
Hi. I don't know where the screenshot is coming from, but I'm assuming it's a container management dashboard. This image doesn't store any data in `/var/www/src`, so that's why it's empty.
