### ISSUE TITLE
MYSQL_PORT variable external database

### ISSUE THREAD

**Issue by zer0ish** [devinsolutions/docker-osticket#48]
Hello,

I'm trying to install this on my unraid server and when I put the direct database ip, username and password, all variables, it doesn't work due to it not having a port listed. My MariaDB container aborts the connection because of the no port.
![image](https://github.com/devinsolutions/docker-osticket/assets/29928635/a695353d-c8d7-4bda-92ef-9ec497271aec)

When I add the port to the ip, ie: 1.1.1.1:3306 it get stuck waiting for TCP connection.
![image](https://github.com/devinsolutions/docker-osticket/assets/29928635/33da1101-ba5b-4ce0-a11a-eab4dfdb651b)

It goes through waiting for about 2 minute or so then stops the container since it can't connect.
My MariaDB container doesn't receive a connection request.

I added the Variable MYSQL_PORT to see if that would work and removed the port from the MYSQL_HOST variable but it doesn't notice the port.

Could the MYSQL_PORT variable be added to the container?

I'm not sure this would fix the issue.

My joomla website and Nextcloud have no issues with connecting to the database.

Even when using the hostname of the MariaDB container(MariaDB) it just waits for the TCP connection.

**Comment by Darigitin** [comment]
Having the exact same issue

**Comment by DesktopMasters** [comment]
I too am having this issue.  I would love a solution.  I tried this on two different UnRAID servers with the same result.

**Comment by Discolor3182** [comment]
Same issue with Unraid.

**Comment by DesktopMasters** [comment]
I actually got around this on UnRAID.. but it was such a wonky solution I did not bother posting it... 
If you are not using Unraid this will still likely work as nothing here is specific to unraid.
This could likely be fixed from the container image its self during setup.
Here you go...

Assuming the container name is "osTICKET" Run the following commands to fix it...
1. Copy the file out of the container: docker cp osTICKET:/usr/local/src/osticket/setup/inc/class.installer.php class.installer.php
2. Edit the "class.installer.php" file and find the line with the following on it: $this->errors['username']=__('Bad username');
3. Then remark out that line and the one above it by putting "//" (no quotes)  at the front of the line.
4. Copy it back: docker cp  class.installer.php osTICKET:/usr/local/src/osticket/setup/inc/class.installer.php
5. Remove the old file (cleanup): rm  class.installer.php
6. Start the container.

**Comment by zer0ish** [comment]
> I actually got around this on UnRAID.. but it was such a wonky solution I did not bother posting it... If you are not using Unraid this will still likely work as nothing here is specific to unraid. This could likely be fixed from the container image its self during setup. Here you go...
> 
> Assuming the container name is "osTICKET" Run the following commands to fix it...
> 
> 1. Copy the file out of the container: docker cp osTICKET:/usr/local/src/osticket/setup/inc/class.installer.php class.installer.php
> 2. Edit the "class.installer.php" file and find the line with the following on it: $this->errors['username']=__('Bad username');
> 3. Then remark out that line and the one above it by putting "//" (no quotes)  at the front of the line.
> 4. Copy it back: docker cp  class.installer.php osTICKET:/usr/local/src/osticket/setup/inc/class.installer.php
> 5. Remove the old file (cleanup): rm  class.installer.php
> 6. Start the container.

This didn't work for me.

But I just tried to re-install it and it works now. I assume one of the updates since this report resolved it.

**Comment by DesktopMasters** [comment]
👍
