### ISSUE TITLE
--mount option requires BuildKit

### ISSUE THREAD

**Issue by mpolinowski** [devinsolutions/docker-osticket#53]
# Issue :: Docker Image Build Fails

> `Step 4/11 : RUN --mount=type=bind,source=utils/verify-plugin.php,target=/tmp/verify-plugin.php,readonly
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled`

This happens with newer Docker versions:

```
docker version

Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996600
 Built:             Wed Jul 26 21:44:58 2023
 OS/Arch:           linux/amd64
 Context:           default
```

I am not yet familiar with BuildKit. But a quick-fix is to replace the __RUN__ mount in [build step 4](https://github.com/devinsolutions/docker-osticket/blob/dcab9ce4ef4d665e45e93f4a04bb9e66d28631ea/Dockerfile#L66) with a __COPY__:

```
COPY utils/verify-plugin.php /tmp/verify-plugin.php

RUN set -ex; \
...
```

**Comment by lubo** [comment]
Hi. The error message is self-explanatory and we don't provide support for Docker. `COPY` is not used because the script is not supposed to be preserved in the image. Just install BuildKit.
