### ISSUE TITLE
Upgrade from 1.11 to 1.12

### ISSUE THREAD

**Issue by DrrMrr** [devinsolutions/docker-osticket#6]
Hi,

is there any manual on how to upgrade from one version to another. 

Thank you and best regards
Damjan

**Comment by lubo** [comment]
Hi. There's no manual, but besides the obvious change of the tag, there's nothing else specific to this image that you have to do. Do you have any specific questions or do you face any particular problems?

**Comment by DrrMrr** [comment]
Hi Lubo,

not thank you for your answer. I will make a backup and try as you have described. I was just asking, cause I didn't know if it would work as you have described.

Best regards
D.
